# Generated by Django 5.0.6 on 2024-06-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('user_name', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(default=None, max_length=150, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('age', models.DurationField(default=None)),
                ('dob', models.DateField(default=None)),
                ('isAdult', models.BooleanField(default=False)),
                ('address', models.TextField(default=None)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'other')], default=None, max_length=1)),
                ('education', models.CharField(choices=[('HS', 'HighSchool'), ('SC', 'SecondarySchool'), ('UG', 'UnderGraduate'), ('PG', 'PostGraduate')], default=None, max_length=2)),
                ('phone_number', models.CharField(max_length=10)),
                ('profile_picture', models.ImageField(upload_to='media/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
